# Generated by Django 3.2.4 on 2021-06-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('stock', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=30)),
            ],
        ),
    ]
