# Generated by Django 3.2.4 on 2021-06-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='image_url',
            field=models.CharField(max_length=2083),
        ),
    ]
